apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx-public"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    # This secret has to be created manually and should contain the CA certificate that has signed
    # the client certs
    nginx.ingress.kubernetes.io/auth-tls-secret: "aggregation/ingress-tls-client-ca"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: public-ingress
  namespace: aggregation
spec:
  rules:
  - host: aggregation2.{{ .Values.Environment }}.{{ .Values.Cluster }}.tink.se
    http:
      paths:
      - backend:
          serviceName: aggregation
          servicePort: 443
        path: /
  - host: aggregation.{{ .Values.Environment }}.{{ .Values.Cluster }}.tink.se
    http:
      paths:
      - backend:
          serviceName: aggregation
          servicePort: 443
        path: /
  tls:
  - hosts:
    - aggregation2.{{ .Values.Environment }}.{{ .Values.Cluster }}.tink.se
    - aggregation.{{ .Values.Environment }}.{{ .Values.Cluster }}.tink.se
    secretName: ingress-tls
