apiVersion: v1
kind: Service
metadata:
  name: aggregation
  namespace: aggregation
spec:
  selector:
    app: aggregation-service
  ports:
  - port: 443
    targetPort: https-api
    name: https-api
  - port: 80
    targetPort: http-api
    name: http-api

{{- if eq "local" .Values.Cluster }}
---
apiVersion: v1
kind: Service
metadata:
  name: aggregation-nodeport
  namespace: aggregation
spec:
  selector:
    app: aggregation-service
  ports:
  - port: 8080
    targetPort: http-api
    name: http-api
    nodePort: 31008
  type: NodePort
{{ end }}
