apiVersion: v1
kind: Service
metadata:
  name: aggregation
  namespace: aggregation
spec:
  selector:
    app: aggregation-service
  ports:
    - port: 443
      targetPort: https-api
      name: https-api

  {{- if eq "local" .Values.Cluster }}
---
apiVersion: v1
kind: Service
metadata:
  name: aggregation-nodeport
  namespace: aggregation
spec:
  selector:
    app: aggregation-service
  ports:
    - port: 443
      targetPort: https-api
      name: https-api
      nodePort: 31011
  type: NodePort
  {{ end }}
